[mgr]
ratio = [0, 1, 1]
sort_by = "natural"

[preview]
tab_size = 8
max_width = 9999
max_height = 9999
image_filter = "lanczos3"
image_quality = 90

[plugin]
prepend_previewers = [ { mime = "application/{json,ndjson}", run = "code" } ]
