shell_integration no-cursor
include current-theme.conf
map ctrl+shift+t new_tab_with_cwd
font_size 10.5

# Do not open links with a plain left click.
# XXX: this solution is hard to maintain.
mouse_map left click ungrabbed mouse_handle_click selection prompt
